// div.v

// Generated using ACDS version 19.2 57

`timescale 1 ps / 1 ps
module div (
		input  wire [7:0] numer,    //  lpm_divide_input.numer
		input  wire [7:0] denom,    //                  .denom
		output wire [7:0] quotient, // lpm_divide_output.quotient
		output wire [7:0] remain    //                  .remain
	);

	div_lpm_divide_191_56nrcay lpm_divide_0 (
		.numer    (numer),    //   input,  width = 8,  lpm_divide_input.numer
		.denom    (denom),    //   input,  width = 8,                  .denom
		.quotient (quotient), //  output,  width = 8, lpm_divide_output.quotient
		.remain   (remain)    //  output,  width = 8,                  .remain
	);

endmodule
