// mu_afu_dma_clock.v

// Generated using ACDS version 19.2 57

`timescale 1 ps / 1 ps
module mu_afu_dma_clock (
		input  wire  in_clk,  //  in_clk.clk
		output wire  out_clk  // out_clk.clk
	);

	assign out_clk = in_clk;

endmodule
