// matmul_afu_pgm_ram.v

// Generated using ACDS version 19.2 57

`timescale 1 ps / 1 ps
module matmul_afu_pgm_ram (
		input  wire [5:0]  address,     //     s1.address
		input  wire        clken,       //       .clken
		input  wire        chipselect,  //       .chipselect
		input  wire        write,       //       .write
		output wire [63:0] readdata,    //       .readdata
		input  wire [63:0] writedata,   //       .writedata
		input  wire [7:0]  byteenable,  //       .byteenable
		input  wire [5:0]  address2,    //     s2.address
		input  wire        chipselect2, //       .chipselect
		input  wire        clken2,      //       .clken
		input  wire        write2,      //       .write
		output wire [63:0] readdata2,   //       .readdata
		input  wire [63:0] writedata2,  //       .writedata
		input  wire [7:0]  byteenable2, //       .byteenable
		input  wire        clk,         //   clk1.clk
		input  wire        reset        // reset1.reset
	);

	matmul_afu_pgm_ram_altera_avalon_onchip_memory2_191_l4xuxyy matmul_afu_pgm_ram (
		.address     (address),     //   input,   width = 6,     s1.address
		.clken       (clken),       //   input,   width = 1,       .clken
		.chipselect  (chipselect),  //   input,   width = 1,       .chipselect
		.write       (write),       //   input,   width = 1,       .write
		.readdata    (readdata),    //  output,  width = 64,       .readdata
		.writedata   (writedata),   //   input,  width = 64,       .writedata
		.byteenable  (byteenable),  //   input,   width = 8,       .byteenable
		.address2    (address2),    //   input,   width = 6,     s2.address
		.chipselect2 (chipselect2), //   input,   width = 1,       .chipselect
		.clken2      (clken2),      //   input,   width = 1,       .clken
		.write2      (write2),      //   input,   width = 1,       .write
		.readdata2   (readdata2),   //  output,  width = 64,       .readdata
		.writedata2  (writedata2),  //   input,  width = 64,       .writedata
		.byteenable2 (byteenable2), //   input,   width = 8,       .byteenable
		.clk         (clk),         //   input,   width = 1,   clk1.clk
		.reset       (reset),       //   input,   width = 1, reset1.reset
		.freeze      (1'b0),        // (terminated),                     
		.reset_req   (1'b0)         // (terminated),                     
	);

endmodule
